### ISSUE TITLE
Busted 2.0

### ISSUE THREAD

**Issue by DorianGray** [lunarmodules/busted#318]
This is the master issue for the 2.0 goal.

Issues that still need to be solved before release:
- [x] https://github.com/Olivine-Labs/busted/issues/299
- [x] https://github.com/Olivine-Labs/busted/issues/270 - specifically, test that pl.strict works.
- [ ] https://github.com/Olivine-Labs/busted/issues/253 - we need to reimplement async, preferably with choice of async runner being defined by the test, not by busted.
- [x] https://github.com/Olivine-Labs/busted/issues/115 - .busted Tasks. This is an unbelievably useful feature, and should be easy to implement.
- [x] https://github.com/Olivine-Labs/busted/issues/62 - just needs testing afaik
- [ ] https://github.com/Olivine-Labs/busted/issues/198 - docs
- [x] https://github.com/Olivine-Labs/busted/issues/320

Nice to haves, but not required for 2.0. I will try to investigate these, at least running test files in each their own thread using lua lanes. Recent improvements in the build process for lualanes makes this feasible.
- [ ] https://github.com/Olivine-Labs/busted/issues/48
- [ ] https://github.com/Olivine-Labs/busted/issues/49

...and finally
- [x] https://github.com/Olivine-Labs/busted/issues/310

**Comment by DorianGray** [comment]
@Olivine-Labs/busted

**Comment by DorianGray** [comment]
@o-lim @naartjie @lipp

**Comment by naartjie** [comment]
I can help with #198

**Comment by o-lim** [comment]
@DorianGray I don't quite understand what #115 is all about.  It seems to discuss several different options regarding .busted tasks, some of which involve handing over the behavior to `lua_cliargs`.  Some clarification would be helpful.

Are you looking for a file format change to ini, json, etc., or a global key that applies to all tasks, or having several pre-configured locations for the .busted file?

**Comment by alerque** [comment]
Closing this as the timeline and milestone contents for 2.x kind of changed over time. Busted 2.x-rcN knid of became the defacto version to use for years and 2.0 was eventually released without async. We've moved on from that and it would be nice to have but is not holding up releases being cut at this point. The other things on this list are open issues and tracked separately and not as part of a past 2.0 milestone.
